// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sppbfdrsrnshdmprpcxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwcGJmZHJzcm5zaGRtcHJwY3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzE0MjEsImV4cCI6MjA2OTM0NzQyMX0.0sbMJ2cR_olWa4QBy0k9HXQLGn6wAILKy8YC8x8oLJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});